feat(icons): add percentage icon
launchdarkly/launchpad-ui pull request #1434
Opened 2024-10-04 20:05 UTC by mguoynes

## Summary

add percentage icon because this design calls for it https://www.figma.com/design/EGmc0e9SX1i5pk75ukLBMH/RG-refresh?node-id=1246-8127&node-type=instance&m=dev

## Screenshots (if appropriate):

![Google Chrome 2024-10-04 16 03 37](https://github.com/user-attachments/assets/ca58d6f0-3a9a-495d-9faa-175c63861986)

## Testing approaches

2024-10-04 20:12 UTC, Niznikr commented on packages/icons/src/img/sprite.svg
> -    <symbol viewBox="0 0 20 20" id="lp-icon-chart-cube-root">
We don't want to delete these

2024-10-04 20:13 UTC, Niznikr commented on packages/icons/src/types.ts
> +	'percentage',
should be after `pause`

2024-10-04 20:50 UTC, Niznikr requested changes, later dismissed
Looks like you accidentally deleted a couple icons 😅

2024-10-17 15:15 UTC, mguoynes commented
> Member

Fixed this

2024-10-22 21:50 UTC, mguoynes commented
We decided to go another direction and this icon is not strictly needed.

2024-10-28 17:54 UTC, carmenquan commented
@mguoynes or @mattdaviscodes (whoever is driving this now) In the thread Launchpad team mentions we need to change to the tabler % icon
https://launchdarkly.slack.com/archives/C03DH955TMW/p1729779071501719

2024-10-29 13:31 UTC, Niznikr approved these changes

2024-10-29 17:14 UTC, merged