Jagarnica/sc 213825/flag status UI updates
launchdarkly/launchpad-ui pull request #986
Opened 2023-09-01 01:25 UTC by jagarnica

## Summary

## Screenshots (if appropriate):

## Testing approaches

2023-09-01 20:10 UTC, vroske-ld approved these changes

2023-09-05 13:13 UTC, Niznikr commented on .changeset/ninety-ravens-argue.md
> +'@launchpad-ui/icons': minor
```suggestion
'@launchpad-ui/icons': patch
```
Non-breaking `0.x` versioning changes

2023-09-05 13:13 UTC, Niznikr requested changes
The lockfile changes seem undesired. What version of pnpm are you using?

2023-09-05 16:55 UTC, jagarnica commented
> The lockfile changes seem undesired. What version of pnpm are you using?

I was using an earlier version at first but I then upgraded to 8.7.1. I was on v7 but I had some issues with it

2023-09-05 17:02 UTC, Niznikr commented
Could you revert the changes to the lockfile?

2023-09-05 18:19 UTC, jagarnica commented
> Could you revert the changes to the lockfile?

Absolutely! I think I found how I caused that. I just reverted those changes now.

2023-09-05 19:33 UTC, Niznikr approved these changes

2023-09-05 23:04 UTC, merged